import Avatar from "@/components/Avatar";
import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import SearchTab from "@/components/SearchTab";
import Footer from "@/components/Footer";
import useDeviceSize from "@/lib/useDeviceSize";

export default function Home() {
  const [width] = useDeviceSize();
  const isMobile = width <= 600;

  return (
    <>
      <Head>
        <title>Google</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className="flex text-sm text-gray-700 w-full">
        <div className="flex space-x-4 items-center absolute top-4 right-4 justify-between w-[90%] md:w-auto">
          <div className="flex space-x-4">
            {" "}
            <Link href="https://mail.google.com/mail/">
              <p className="link">Gmail</p>
            </Link>
            <Link href="https://photos.google.com/">
              <p className="link">Images</p>
            </Link>
          </div>
          <div className="flex space-x-4">
            <Link href="https://www.google.com.ng/intl/en-GB/about/products?tab=rh">
              <svg
                className="text-gray-300 h-8 w-8 p-1 rounded-full hover:bg-gray-100 cursor-pointer"
                focusable="false"
                viewBox="0 0 24 24"
              >
                <path d="M6,8c1.1,0 2,-0.9 2,-2s-0.9,-2 -2,-2 -2,0.9 -2,2 0.9,2 2,2zM12,20c1.1,0 2,-0.9 2,-2s-0.9,-2 -2,-2 -2,0.9 -2,2 0.9,2 2,2zM6,20c1.1,0 2,-0.9 2,-2s-0.9,-2 -2,-2 -2,0.9 -2,2 0.9,2 2,2zM6,14c1.1,0 2,-0.9 2,-2s-0.9,-2 -2,-2 -2,0.9 -2,2 0.9,2 2,2zM12,14c1.1,0 2,-0.9 2,-2s-0.9,-2 -2,-2 -2,0.9 -2,2 0.9,2 2,2zM16,6c0,1.1 0.9,2 2,2s2,-0.9 2,-2 -0.9,-2 -2,-2 -2,0.9 -2,2zM12,8c1.1,0 2,-0.9 2,-2s-0.9,-2 -2,-2 -2,0.9 -2,2 0.9,2 2,2zM18,14c1.1,0 2,-0.9 2,-2s-0.9,-2 -2,-2 -2,0.9 -2,2 0.9,2 2,2zM18,20c1.1,0 2,-0.9 2,-2s-0.9,-2 -2,-2 -2,0.9 -2,2 0.9,2 2,2z"></path>
              </svg>
            </Link>
            <Avatar
              url="https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Default_pfp.svg/340px-Default_pfp.svg.png?20220226140232"
              // url="https://lh3.googleusercontent.com/ogw/AAEL6sjHUuJEzokl1bNe-TzdoAymNKB--G2zWt4czTUP7Q"
              href="https://accounts.google.com/SignOutOptions?hl=en-GB&continue=https://www.google.com%3Fhl%3Den-GB"
            />
          </div>
        </div>
      </header>

      <main>
        <form className="flex flex-col items-center mt-40 md:mt-20 flex-grow">
          {isMobile ? (
            <Image
              width={160}
              height={56}
              alt="Google Homepage"
              className="m-3"
              src="https://www.google.com/images/branding/googlelogo/2x/googlelogo_color_160x56dp.png"
            />
          ) : (
            <Image
              width={272}
              height={92}
              alt="Google Homepage"
              className="m-5"
              src="https://www.google.com/images/branding/googlelogo/1x/googlelogo_color_272x92dp.png"
            />
          )}
          <SearchTab />
        </form>
      </main>

      <Footer />
    </>
  );
}
