import Head from "next/head";
// import Image from "next/image";

export default function Home() {
  return (
    <>
      <Head>
        <title>Google</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* Header */}
      <header>
        {/* Left */}
        <div className="flex space-x-4 items-center">
          <a href="https://github.com/joshuaedo/google#readme">
            <p>About</p>
          </a>
          <a href="https://chrome.google.com/webstore/">
            <p>Store</p>
          </a>
        </div>
        {/* Right */}
        <div className="flex space-x-4 items-center">
          <a href="https://mail.google.com/mail/">
            <p>Gmail</p>
          </a>
          <a href="https://photos.google.com/">
            <p>Images</p>
          </a>
        </div>
        {/* Icon */}
        {/* Avatar */}
      </header>
      {/* Body */}
      <main>
        <h1 className="m-5 font-bold">Google!</h1>
      </main>
      {/* Footer */}
      <footer></footer>
    </>
  );
}
